"""Fine-tuning pipeline for BETO (BERT Spanish) on the tweet classification task.

This script prepares the dataset, tokenizes tweets using the BETO tokenizer,
builds a `BertForSequenceClassification` model, and fine-tunes it using the
Hugging Face `Trainer` API. The script is intended to be runnable as a
stand-alone process to produce a fine-tuned model saved under
``./modelo_beto_final`` and a short metrics report written to
``metricas_evaluacion_entrenamiento.txt``.

Requirements and inputs
------------------------
- Python packages: transformers, torch, sklearn, pandas, numpy
- Input CSV: ``files/data_train_cleaned2.csv`` containing at least
    ``tweet_text_clean`` and ``class`` columns. Classes must be 'control'
    and 'anorexia'.

Outputs
-------
- Saved model and tokenizer under ``./modelo_beto_final``
- Evaluation metrics written to ``metricas_evaluacion_entrenamiento.txt``

Notes
-----
- The script tokenizes to ``max_length=128`` and uses a 70/30 train/val
    split (stratified). It configures early stopping and saves the best
    checkpoint by F1-score. The code assumes GPU if available but will
    run on CPU as fallback.
"""

import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score, recall_score
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import TrainingArguments, Trainer, EarlyStoppingCallback
from torch.utils.data import Dataset
from datetime import datetime
import os

# =====================================================================
# 1. Definición de la clase Dataset
# =====================================================================
class TweetDataset(Dataset):
    """
    A custom PyTorch Dataset for handling tokenized text encodings and labels.

    This class wraps the text encodings generated by a Hugging Face tokenizer
    and their corresponding integer labels, making them compatible with
    PyTorch's DataLoader for model training and evaluation.

    Parameters
    ----------
    encodings : dict
        A dictionary containing the tokenized outputs (e.g., 'input_ids',
        'attention_mask') where each value is a list or array of sequences.
    labels : list or array-like
        A sequence of integer labels corresponding to the text data.
    """

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        """
        Returns the total number of samples in the dataset.

        Returns
        -------
        int
            The length of the dataset based on the labels list.
        """
        return len(self.labels)

    def __getitem__(self, idx):
        """
        Retrieves a single sample (features and label) at the specified index.

        Parameters
        ----------
        idx : int
            The index of the sample to retrieve.

        Returns
        -------
        dict
            A dictionary containing the tensor representations of the text
            encodings and the corresponding label for the specified index.
        """
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(int(self.labels[idx]))
        return item

# =====================================================================
# 2. Cargar Tokenizer
# =====================================================================
tokenizer = BertTokenizer.from_pretrained("dccuchile/bert-base-spanish-wwm-cased")

# =====================================================================
# 3. Carga y preparación de datos
# =====================================================================
df = pd.read_csv("files/data_train_cleaned2.csv", encoding="utf-8")

if df.empty:
    raise ValueError("El archivo CSV está vacío.")

# Limpieza de clases y filtrado preventivo de NaNs para evitar colapsos en PyTorch
df["class_clean"] = df["class"].astype(str).str.strip().str.lower()

mapeo_clases = {
    "control": 0,
    "anorexia": 1
}

# Identificar y remover registros con etiquetas inválidas antes de tokenizar
clases_validas = df["class_clean"].isin(mapeo_clases.keys())
if not clases_validas.all():
    invalid_count = (~clases_validas).sum()
    print(f"¡ADVERTENCIA! Filtrando {invalid_count} registros con etiquetas desconocidas.")
    df = df[clases_validas].copy()

# Mapear las clases a IDs numéricos estables
df["label_id"] = df["class_clean"].map(mapeo_clases)

X = df["tweet_text_clean"].fillna("").astype(str).tolist()
y = df["label_id"].tolist()

print(f"Datos cargados y limpiados correctamente. Total muestras válidas: {len(X)}")

# --- Split de Entrenamiento / Validación (70/30) ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Tokenizar los textos de forma independiente
train_encodings = tokenizer(X_train, padding=True, truncation=True, max_length=128)
test_encodings = tokenizer(X_test, padding=True, truncation=True, max_length=128)

# Crear los objetos Dataset para alimentar a PyTorch
train_dataset = TweetDataset(train_encodings, y_train)
test_dataset = TweetDataset(test_encodings, y_test)

# =====================================================================
# 5. Cargar BETO preparado para clasificación de secuencias
# =====================================================================
num_clases = 2 
modelo = BertForSequenceClassification.from_pretrained(
    "dccuchile/bert-base-spanish-wwm-cased", 
    num_labels=num_clases
)

# Dejamos todas las capas descongeladas para que puedan adaptarse de forma suave.
for name, param in modelo.bert.named_parameters():
    param.requires_grad = True

print("Todas las capas están activas para el ajuste fino. Optimizando balance...")

# =====================================================================
# 6. Definir métricas de evaluación
# =====================================================================
def compute_metrics(pred):
    """
    Computes performance metrics for a sequence classification model.

    This function takes the raw predictions and ground truth labels from
    the model, applies a softmax function to calculate the AUC for the
    positive class, and computes standard binary classification metrics
    including accuracy, precision, recall, F1-score, and specificity
    (which is calculated as the recall of the negative class).

    Parameters
    ----------
    pred : transformers.trainer_utils.EvalPrediction
        An object containing `predictions` (logits returned by the model)
        and `label_ids` (ground truth labels).

    Returns
    -------
    dict
        A dictionary containing the calculated metrics: 'accuracy', 'f1',
        'precision', 'recall', 'specificity', and 'auc'.
    """
    labels = pred.label_ids
    logits = pred.predictions
    preds = logits.argmax(-1)
    
    # Softmax para obtener las probabilidades de la clase positiva (anorexia)
    probs = torch.softmax(torch.tensor(logits), dim=-1)[:, 1].numpy()
    auc = roc_auc_score(labels, probs)
    
    # Specificity (Recall de la clase control)
    specificity = recall_score(labels, preds, pos_label=0)
    
    # Métricas estándar binarias
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary', zero_division=0)
    acc = accuracy_score(labels, preds)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'specificity': specificity,
        'auc': auc
    }

# =====================================================================
# 7. Definir Hiperparámetros BALANCEADOS (Evita Underfitting y Overfitting)
# =====================================================================
training_args = TrainingArguments(
    output_dir='./resultados_beto',          
    num_train_epochs=8,                        # 4 epochs dan margen al Early Stopping para decidir el punto óptimo
    per_device_train_batch_size=16,            # Batch size de 16 para actualizaciones frecuentes de gradiente
    per_device_eval_batch_size=32,           
    learning_rate=2e-5,                        # El "sweet spot" estándar para modelos BERT-base
    weight_decay=0.01,                         # Regularización estándar balanceada
    warmup_ratio=0.1,                          # Calentamiento lineal inicial del 10% de los pasos
    lr_scheduler_type="cosine",                # Decaimiento en coseno para suavizar el entrenamiento al final
    eval_strategy="epoch",                   
    save_strategy="epoch",                    
    load_best_model_at_end=True,               # Revierte al mejor checkpoint según la métrica asignada abajo
    metric_for_best_model="f1",                # Selecciona la mejor versión basándose en el F1-Score general
    greater_is_better=True,
    save_total_limit=1,                        # Borra checkpoints anteriores para ahorrar espacio en disco (~440MB c/u)
    logging_steps=10,
)

# =====================================================================
# 8. Inicializar el Trainer con Paciencia Balanceada
# =====================================================================
trainer = Trainer(
    model=modelo,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
    # Paciencia de 2 epochs para permitirle estabilizarse si una epoch oscila por ruido
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

print("Iniciando el entrenamiento...")

# =====================================================================
# 9. Entrenar el modelo
# =====================================================================
trainer.train()

# =====================================================================
# 10. Evaluar en el conjunto de prueba (Regresará el mejor modelo guardado)
# =====================================================================
print("Evaluando el mejor modelo encontrado...")
resultados = trainer.evaluate()
print("Resultados de la evaluación:", resultados)

# =====================================================================
# 11. Guardar el mejor modelo definitivo
# =====================================================================
ruta_guardado = "./modelo_beto_final"
print(f"Guardando el modelo definitivo y el tokenizador en: {ruta_guardado}")

trainer.save_model(ruta_guardado)
tokenizer.save_pretrained(ruta_guardado)

# --- GUARDAR MÉTRICAS EN UN TXT ---
nombre_archivo = "metricas_evaluacion_entrenamiento.txt"
ahora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

with open(nombre_archivo, "w", encoding="utf-8") as f:
    f.write("==================================================\n")
    f.write(f"REPORTE DE EVALUACIÓN - BETO FINETUNED\n")
    f.write(f"Fecha y Hora: {ahora}\n")
    f.write("==================================================\n\n")
    
    for metrica, valor in resultados.items():
        if isinstance(valor, float) and "time" not in metrica and "per_second" not in metrica:
            f.write(f"{metrica:<30}: {valor:.4f}\n")
        else:
            f.write(f"{metrica:<30}: {valor}\n")
            
    f.write("\n==================================================\n")

print(f"¡Métricas guardadas con éxito en '{nombre_archivo}'!")