import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score, recall_score
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import TrainingArguments, Trainer
from torch.utils.data import Dataset
from datetime import datetime

# 1. Definición de la clase Dataset
class TweetDataset(Dataset):
    """
    A custom PyTorch Dataset for handling tokenized text encodings and labels.

    This class wraps the text encodings generated by a Hugging Face tokenizer
    and their corresponding integer labels, making them compatible with
    PyTorch's DataLoader for model training and evaluation.

    Parameters
    ----------
    encodings : dict
        A dictionary containing the tokenized outputs (e.g., 'input_ids',
        'attention_mask') where each value is a list or array of sequences.
    labels : list or array-like
        A sequence of integer labels corresponding to the text data.
    """

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        """
        Returns the total number of samples in the dataset.

        Returns
        -------
        int
            The length of the dataset based on the labels list.
        """
        return len(self.labels)

    def __getitem__(self, idx):
        """
        Retrieves a single sample (features and label) at the specified index.

        Parameters
        ----------
        idx : int
            The index of the sample to retrieve.

        Returns
        -------
        dict
            A dictionary containing the tensor representations of the text
            encodings and the corresponding label for the specified index.
        """
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(int(self.labels[idx]))
        return item


def prepare_datasets_and_model(file_path="files/data_train_cleaned2.csv"):
    """
    Loads data, preprocesses labels, tokenizes text, and initializes the BERT model.

    This function executes the complete data preparation pipeline for fine-tuning
    a Spanish BERT (BETO) model. It reads tweet data from a CSV, normalizes and
    maps the string classes ('control' -> 0, 'anorexia' -> 1), splits the data
    into stratified training (70%) and testing (30%) sets, applies the tokenizer,
    creates the PyTorch Dataset objects, and initializes the sequence classifier.

    Parameters
    ----------
    file_path : str, optional
        The path to the CSV file containing the cleaned text data and classes
        (default is "files/data_train_cleaned2.csv").

    Returns
    -------
    tuple
        A 4-element tuple containing:
        - train_dataset (TweetDataset): The PyTorch dataset for training.
        - test_dataset (TweetDataset): The PyTorch dataset for testing.
        - tokenizer (BertTokenizer): The loaded Spanish BERT tokenizer.
        - modelo (BertForSequenceClassification): The initialized classification model.

    Raises
    ------
    ValueError
        If the extracted text data feature set (X) is completely empty.
    """
    # 2. Cargar Tokenizer
    tokenizer = BertTokenizer.from_pretrained("dccuchile/bert-base-spanish-wwm-cased")

    # 3. Carga y preparación de datos
    df = pd.read_csv(file_path, encoding="utf-8")

    X = df["tweet_text_clean"]
    y = df["class"]

    if X.empty:
        raise ValueError("No data")
    else:
        print("Datos cargados correctamente. Listo para procesar.")

    # Preparar textos y etiquetas
    texts = X.fillna("").astype(str).tolist()

    # --- CORRECCIÓN DEL MAPEO DE CLASES ---
    # 1. Limpiamos espacios invisibles y pasamos a minúsculas para evitar errores de tipeo
    y_limpio = y.astype(str).str.strip().str.lower()

    # 2. Forzamos el diccionario para que no cambie jamás
    mapeo_clases = {
        "control": 0,
        "anorexia": 1
    }

    # 3. Aplicamos el mapa y lo convertimos a lista
    label_ids = y_limpio.map(mapeo_clases).tolist()

    # Pequeña validación para asegurarnos de que no haya nulos por palabras mal escritas
    if pd.Series(label_ids).isna().any():
        print("¡ADVERTENCIA! Hay palabras en tu columna 'class' que no son ni 'anorexia' ni 'control'.")

    # --- Entrenamiento 70/30 ---
    X_train, X_test, y_train, y_test = train_test_split(
        texts, label_ids, test_size=0.3, random_state=42, stratify=label_ids
    )

    # Tokenizar por separado para cada split
    train_encodings = tokenizer(X_train, padding=True, truncation=True, max_length=128)
    test_encodings = tokenizer(X_test, padding=True, truncation=True, max_length=128)

    # 4. Crear los objetos Dataset para PyTorch
    train_dataset = TweetDataset(train_encodings, y_train)
    test_dataset = TweetDataset(test_encodings, y_test)

    # 5. Cargar BETO preparado para clasificación de secuencias
    num_clases = 2
    modelo = BertForSequenceClassification.from_pretrained(
        "dccuchile/bert-base-spanish-wwm-cased",
        num_labels=num_clases
    )

    return train_dataset, test_dataset, tokenizer, modelo

# 6. Definir métricas de evaluación (ACTUALIZADO CON SPECIFICITY Y AUC)
def compute_metrics(pred):
    """
    Computes performance metrics for a sequence classification model.

    This function takes the raw predictions and ground truth labels from
    the model, applies a softmax function to calculate the AUC for the
    positive class, and computes standard binary classification metrics
    including accuracy, precision, recall, F1-score, and specificity
    (which is calculated as the recall of the negative class).

    Parameters
    ----------
    pred : transformers.trainer_utils.EvalPrediction
        An object containing `predictions` (logits returned by the model)
        and `label_ids` (ground truth labels).

    Returns
    -------
    dict
        A dictionary containing the calculated metrics: 'accuracy', 'f1',
        'precision', 'recall', 'specificity', and 'auc'.
    """
    labels = pred.label_ids
    logits = pred.predictions
    preds = logits.argmax(-1)

    # 1. Calcular AUC:
    # El modelo nos devuelve "logits" (números crudos). Los convertimos a probabilidades
    # de 0 a 1 usando la función Softmax, y extraemos solo las probabilidades de la clase 1.
    probs = torch.softmax(torch.tensor(logits), dim=-1)[:, 1].numpy()
    auc = roc_auc_score(labels, probs)

    # 2. Calcular Specificity (Especificidad):
    # La especificidad equivale matemáticamente al Recall de la clase negativa (0).
    specificity = recall_score(labels, preds, pos_label=0)

    # 3. Métricas estándar
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'specificity': specificity,
        'auc': auc
    }


def train_evaluate_and_save(modelo, tokenizer, train_dataset, test_dataset):
    """
    Configures, trains, evaluates, and saves the Hugging Face BERT model.

    This function defines the hyperparameter configuration using TrainingArguments
    and initializes a Trainer instance. It executes the training loop on the
    provided training dataset, evaluates its performance on the test dataset,
    saves the final model and tokenizer to disk, and exports the evaluation
    metrics to a formatted text file.

    Parameters
    ----------
    modelo : transformers.PreTrainedModel
        The initialized BERT model for sequence classification.
    tokenizer : transformers.PreTrainedTokenizer
        The tokenizer associated with the BERT model.
    train_dataset : torch.utils.data.Dataset
        The prepared dataset for training.
    test_dataset : torch.utils.data.Dataset
        The prepared dataset for evaluation/testing.

    Returns
    -------
    None
    """
    # 7. Definir Hiperparámetros OPTIMIZADOS (TrainingArguments)
    training_args = TrainingArguments(
        output_dir='./resultados_beto',
        num_train_epochs=4,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        learning_rate=1e-5,
        weight_decay=0.01,
        eval_strategy="epoch",  # Evaluar al final de cada epoch para monitorear métricas
        save_strategy="no",  # Evita que se guarden archivos pesados por cada epoch
        load_best_model_at_end=False,  # Requerido al desactivar el guardado
    )

    # 8. Inicializar el Trainer
    trainer = Trainer(
        model=modelo,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics
    )

    print("Iniciando el entrenamiento")

    # 9. Entrenar el modelo
    trainer.train()

    # 10. Evaluar en el conjunto de prueba
    print("Evaluando el modelo")
    resultados = trainer.evaluate()
    print("Resultados de la evaluación:", resultados)

    # 11. Guardar
    print("Guardando el modelo entrenado y el tokenizador en disco...")
    ruta_guardado = "./modelo_beto_final"

    trainer.save_model(ruta_guardado)
    tokenizer.save_pretrained(ruta_guardado)

    # --- NUEVO PASO: GUARDAR MÉTRICAS EN UN TXT ---
    nombre_archivo = "metricas_evaluacion_entrenamiento.txt"

    # Obtenemos la fecha y hora actual para saber cuándo hicimos la prueba
    ahora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with open(nombre_archivo, "w", encoding="utf-8") as f:
        f.write("==================================================\n")
        f.write(f"REPORTE DE EVALUACIÓN - BETO\n")
        f.write(f"Fecha y Hora: {ahora}\n")
        f.write("==================================================\n\n")

        # Recorremos el diccionario de resultados y lo escribimos bonito
        for metrica, valor in resultados.items():
            # Formateamos las métricas flotantes para que no tengan tantos decimales
            if isinstance(valor, float) and "time" not in metrica and "per_second" not in metrica:
                f.write(f"{metrica:<30}: {valor:.4f}\n")
            else:
                f.write(f"{metrica:<30}: {valor}\n")

        f.write("\n==================================================\n")

    print(f"¡Métricas guardadas con éxito en '{nombre_archivo}'!")


