import torch
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, roc_auc_score, recall_score
from transformers import BertTokenizer, BertForSequenceClassification, Trainer
from torch.utils.data import Dataset
from text_cleaner import process_csv2
from datetime import datetime


class TweetDataset(Dataset):
    """
    A custom PyTorch Dataset for handling tokenized text encodings and labels.

    This class wraps the text encodings generated by a Hugging Face tokenizer
    and their corresponding integer labels, making them compatible with
    PyTorch's DataLoader for model training and evaluation.

    Parameters
    ----------
    encodings : dict
        A dictionary containing the tokenized outputs (e.g., 'input_ids',
        'attention_mask') where each value is a list or array of sequences.
    labels : list or array-like
        A sequence of integer labels corresponding to the text data.
    """

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(int(self.labels[idx]))
        return item


def compute_metrics(pred):
    """
    Computes performance metrics for a sequence classification model.

    This function takes the raw predictions and ground truth labels from
    the model, applies a softmax function to calculate the AUC for the
    positive class, and computes standard binary classification metrics
    including accuracy, precision, recall, F1-score, and specificity.

    Parameters
    ----------
    pred : transformers.trainer_utils.EvalPrediction
        An object containing `predictions` (logits returned by the model)
        and `label_ids` (ground truth labels).

    Returns
    -------
    dict
        A dictionary containing the calculated metrics: 'accuracy', 'f1',
        'precision', 'recall', 'specificity', and 'auc'.
    """
    labels = pred.label_ids
    logits = pred.predictions
    preds = logits.argmax(-1)

    probs = torch.softmax(torch.tensor(logits), dim=-1)[:, 1].numpy()
    auc = roc_auc_score(labels, probs)
    specificity = recall_score(labels, preds, pos_label=0)

    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    acc = accuracy_score(labels, preds)

    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall,
        'specificity': specificity,
        'auc': auc
    }


def evaluate_test_data(input_file="data_test_fold1(in).csv",
                       clean_file="data_test_clean2.csv",
                       model_dir="./modelo_beto_final"):
    """
    Evaluates a fine-tuned BERT model on an unseen test dataset.

    This function processes the raw test CSV, loads a previously fine-tuned
    BERT model and tokenizer from disk, prepares the test data by normalizing
    and mapping the class labels, tokenizes the text, and evaluates the
    model using the Hugging Face Trainer. Finally, it exports the evaluation
    metrics to a formatted text file.

    Parameters
    ----------
    input_file : str, optional
        The filename of the raw input test data (default is 'data_test_fold1(in).csv').
    clean_file : str, optional
        The filename for the cleaned output test data (default is 'data_test_clean2.csv').
    model_dir : str, optional
        The directory path where the trained model and tokenizer are saved
        (default is './modelo_beto_final').

    Returns
    -------
    dict
        A dictionary containing the calculated evaluation metrics.
    """
    # Procesar archivo original
    process_csv2(input_file, clean_file, 'tweet_text')

    # Cargar el modelo
    tokenizer_test = BertTokenizer.from_pretrained(model_dir)
    modelo_test = BertForSequenceClassification.from_pretrained(model_dir)

    # Carga y preparación de datos (Asegúrate de que la ruta coincida con tu estructura)
    df = pd.read_csv(f"files/{clean_file}", encoding="utf-8")

    X = df["tweet_text_clean"]
    y = df["class"]

    if X.empty:
        raise ValueError("No data")
    else:
        print("Datos cargados correctamente. Listo para procesar.")

    # Preparar textos y etiquetas
    texts = X.fillna("").astype(str).tolist()

    # --- CORRECCIÓN DEL MAPEO DE CLASES ---
    y_limpio = y.astype(str).str.strip().str.lower()
    mapeo_clases = {
        "control": 0,
        "anorexia": 1
    }
    label_ids = y_limpio.map(mapeo_clases).tolist()

    if pd.Series(label_ids).isna().any():
        print("¡ADVERTENCIA! Hay palabras en tu columna 'class' que no son ni 'anorexia' ni 'control'.")

    # Tokenización y creación de dataset
    test_encodings = tokenizer_test(texts, padding=True, truncation=True, max_length=128)
    dataset = TweetDataset(test_encodings, label_ids)

    # Inicializar Evaluador
    evaluador = Trainer(
        model=modelo_test,
        eval_dataset=dataset,
        compute_metrics=compute_metrics
    )

    # Evaluar
    print("Iniciando evaluación en los nuevos datos de test...")
    resultados = evaluador.evaluate()

    print("\n--- Resultados del Test ---")
    print(resultados)

    # Guardar reporte
    nombre_archivo = "metricas_evaluacion_test.txt"
    ahora = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with open(nombre_archivo, "w", encoding="utf-8") as f:
        f.write("==================================================\n")
        f.write(f"REPORTE DE EVALUACIÓN - BETO\n")
        f.write(f"Fecha y Hora: {ahora}\n")
        f.write("==================================================\n\n")

        for metrica, valor in resultados.items():
            if isinstance(valor, float) and "time" not in metrica and "per_second" not in metrica:
                f.write(f"{metrica:<30}: {valor:.4f}\n")
            else:
                f.write(f"{metrica:<30}: {valor}\n")

        f.write("\n==================================================\n")

    print(f"¡Métricas guardadas con éxito en '{nombre_archivo}'!")

    return resultados


if __name__ == "__main__":
    evaluate_test_data()

